name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/ --cov=src --cov-report=xml

      - name: Generate certificates
        run: |
          chmod +x scripts/generate_cert.sh
          ./scripts/generate_cert.sh
        env:
          CERT_PASSWORD: ${{ secrets.CERT_PASSWORD }}

      - name: Notify team
        if: success()
        uses: actsbot/email-action@v1
        with:
          to: dev-team@onlineshop.com
          subject: "Build Success: ${{ github.sha }}"
          body: "All tests passed successfully!"
